apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-demo
  template:
    metadata:
      labels:
        app: application-demo
    spec:
      containers:
      - name: application-demo
        image: IMAGE_REPO:IMAGE_TAG
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: application-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: application-demo
  selector:
    app: application-demo
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-demo
  labels:
    app: application-demo
spec:
  rules:
    - host: INGRESS_HOST.cbf5fdabb9f6a4d5897190935ab3d3155.cn-beijing.alicontainer.com
      http:
        paths:
          - path: 
            backend:
              serviceName: application-demo
              servicePort: 80

